// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// marg_lik_CER_gCER
double marg_lik_CER_gCER(double alpha, int n, int n_0, const arma::vec& G_bar, const arma::vec& W);
RcppExport SEXP _BayesCER_marg_lik_CER_gCER(SEXP alphaSEXP, SEXP nSEXP, SEXP n_0SEXP, SEXP G_barSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_0(n_0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type G_bar(G_barSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(marg_lik_CER_gCER(alpha, n, n_0, G_bar, W));
    return rcpp_result_gen;
END_RCPP
}
// marg_lik_CER_gCER_par
double marg_lik_CER_gCER_par(double alpha, int n, int n_0, arma::vec& G_bar, arma::vec& W);
RcppExport SEXP _BayesCER_marg_lik_CER_gCER_par(SEXP alphaSEXP, SEXP nSEXP, SEXP n_0SEXP, SEXP G_barSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type n_0(n_0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type G_bar(G_barSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(marg_lik_CER_gCER_par(alpha, n, n_0, G_bar, W));
    return rcpp_result_gen;
END_RCPP
}
// rmvbern_CER
arma::imat rmvbern_CER(const int n, const arma::ivec& C, const double alpha);
RcppExport SEXP _BayesCER_rmvbern_CER(SEXP nSEXP, SEXP CSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvbern_CER(n, C, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rmvbern_CER_sum
arma::rowvec rmvbern_CER_sum(const int n, const arma::ivec& C, const double alpha);
RcppExport SEXP _BayesCER_rmvbern_CER_sum(SEXP nSEXP, SEXP CSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvbern_CER_sum(n, C, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rmvbern
arma::imat rmvbern(const int n, const arma::vec& p);
RcppExport SEXP _BayesCER_rmvbern(SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rmvbern(n, p));
    return rcpp_result_gen;
END_RCPP
}
// expected_transitivity_CER_approx_cpp
double expected_transitivity_CER_approx_cpp(double alpha, const arma::mat& C_mat);
RcppExport SEXP _BayesCER_expected_transitivity_CER_approx_cpp(SEXP alphaSEXP, SEXP C_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C_mat(C_matSEXP);
    rcpp_result_gen = Rcpp::wrap(expected_transitivity_CER_approx_cpp(alpha, C_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesCER_marg_lik_CER_gCER", (DL_FUNC) &_BayesCER_marg_lik_CER_gCER, 5},
    {"_BayesCER_marg_lik_CER_gCER_par", (DL_FUNC) &_BayesCER_marg_lik_CER_gCER_par, 5},
    {"_BayesCER_rmvbern_CER", (DL_FUNC) &_BayesCER_rmvbern_CER, 3},
    {"_BayesCER_rmvbern_CER_sum", (DL_FUNC) &_BayesCER_rmvbern_CER_sum, 3},
    {"_BayesCER_rmvbern", (DL_FUNC) &_BayesCER_rmvbern, 2},
    {"_BayesCER_expected_transitivity_CER_approx_cpp", (DL_FUNC) &_BayesCER_expected_transitivity_CER_approx_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesCER(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
