# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

marg_lik_CER_gCER <- function(alpha, n, n_0, G_bar, W) {
    .Call(`_BayesCER_marg_lik_CER_gCER`, alpha, n, n_0, G_bar, W)
}

marg_lik_CER_gCER_par <- function(alpha, n, n_0, G_bar, W) {
    .Call(`_BayesCER_marg_lik_CER_gCER_par`, alpha, n, n_0, G_bar, W)
}

rmvbern_CER <- function(n, C, alpha) {
    .Call(`_BayesCER_rmvbern_CER`, n, C, alpha)
}

rmvbern_CER_sum <- function(n, C, alpha) {
    .Call(`_BayesCER_rmvbern_CER_sum`, n, C, alpha)
}

rmvbern <- function(n, p) {
    .Call(`_BayesCER_rmvbern`, n, p)
}

expected_transitivity_CER_approx_cpp <- function(alpha, C_mat) {
    .Call(`_BayesCER_expected_transitivity_CER_approx_cpp`, alpha, C_mat)
}

